//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyAsset.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class AccountBook
    {
        public System.Guid Id { get; set; }
        [DisplayName("類別")]
        public int Categoryyy { get; set; }
        [DisplayName("金額")]
        public int Amounttt { get; set; }
        [DisplayName("日期")]
        public System.DateTime Dateee { get; set; }
        [DisplayName("備註")]
        public string Remarkkk { get; set; }
    }
}
